### ISSUE TITLE
when will the first release finally be released?

### ISSUE THREAD

**Issue by strausmann** [WHMCS/sample-notification-module#1]
when will the first release finally be released?

Regards,

Bjoern

**Comment by Baptistecottey** [comment]
You can copy on Email notification system.

It's not encoded !

I've did it to integrate telegram 😃

**Comment by MrMoio** [comment]
@Baptistecottey did you release it for Telegram? :) Would be so good to get integration with Telegram

**Comment by Baptistecottey** [comment]
@MrMoio https://gitlab.com/baaptiisteee/whmcs-notification-telegram/

Feel free to contribute 😄

**Comment by MrMoio** [comment]
@Baptistecottey thank you so much!!! I checked your github first ^^ , i can contribute with translation if needed for sure ;)

**Comment by Baptistecottey** [comment]
All the translation are provided by @WHMCS 
The only things to translate, is that : 
![image](https://user-images.githubusercontent.com/1415941/33267438-c51ed89e-d379-11e7-8124-be4d204ab191.png)

**Comment by Baptistecottey** [comment]
All translations are provided by @WHMCS
The only things you can translate is this : 
![image](https://user-images.githubusercontent.com/1415941/33267469-e7f4fef2-d379-11e7-8277-6fba99604882.png)
